### ISSUE TITLE
Nodes and alphabet

### ISSUE THREAD

**Issue by AntonKrug** [drom/wavedrom#200] opened 2018-07-26 10:26 UTC
Is there a way to escape and give nodes a longer name? Even if it would break the alignment. 

As it's fairly to run out of alphabet or it's tricky to recall all the character meanings when there are over 20 events happening in the diagram.

**Comment by drom** [comment] 2018-07-27 10:32
Duplicate of https://github.com/drom/wavedrom/issues/89

**Closed** 2018-07-27 13:05 UTC
Labels: duplicate
